analyzer:
  contour_minimum_area: 5000
  delta_threshold: 5
  max_fps: 5
  undistort: true
  undistort_balance: 1.0
camera:
  D: '[[-0.06300247530706406], [0.028367414247228113], [-0.018682028009339952], [0.0037199220124150604]]'
  K: '[[539.8606873339231, 0.0, 999.745990731636], [0.0, 540.4889507343736, 541.3382370501859],
    [0.0, 0.0, 1.0]]'
  format: MJPG
  index: 0
  max_fps: 30
  resolution: 1920x1080
  rotation: null
screen:
  activation_period: 10
  backlight_device: /sys/class/backlight/rpi_backlight/bl_power
  color_conv: COLOR_BGR2BGR565
  dtype: uint16
  framebuffer_device: /dev/fb0
  resolution: 480x800
  rotation: ROTATE_90_CLOCKWISE
  touch_device: /dev/input/event1
  undistort: true
  undistort_balance: 1.0
capture:
  enable: true
  preroll: 5
  postroll: 5
  path: capture
stream:
  ip: 0.0.0.0
  port: 8080
